services:
  - type: web
    name: restaurent-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install --registry=https://registry.npmjs.org
    startCommand: node server.js
    autoDeploy: true
